name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Generate environment.ts from secret
        run: |
          mkdir -p src/environments
          echo "$ENV_PRD" > src/environments/environment.ts
        env:
          ENV_PRD: ${{ secrets.ENV_PRD }}

      - name: Build Angular app
        run: npm run build -- --base-href=/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist/$(node -p "require('./angular.json').defaultProject")
          clean: true

